# **Session-2 : Computer Vision Basics with PyTorch**
# Assignment Notebook

This assignment is based on the class presentation on computer vision with PyTorch.

## Instructions

- Work independently.
- Do **not** use AI tools such as ChatGPT, Copilot, Gemini, or similar assistants.
- Use your lecture slides, references and the reference materials  provided in tasks and the putorch documentation sent to you.
- Read each question carefully before filling in the blank or answering the question.
- For code cells, replace only the missing part unless the prompt asks you to write more.
- For question cells, answer in your own words in 2 to 4 clear sentences by adding a text cell.
- Save the completed notebook before submitting it.

## Topics covered

This assignment focuses on:

- A small amount of PyTorch and tensor basics
- Pixels, grayscale images, RGB images, and tensor shapes
- Filters, convolution intuition, and feature maps
- Image classification with a simple fully connected network
- `torchvision` datasets, transforms, augmentation, `DataLoader`, training, and evaluation



## Submission Checklist

- All blanks are filled
- All short answers are written in your own words
- The notebook runs from top to bottom
- The final file is saved before submission


In [6]:
import torch
import numpy as np
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

print("Starter imports loaded.")


Starter imports loaded.


## Task 1: Tensor creation and dtypes

Tensors are the main data structure in PyTorch. Different creation functions are used depending on whether you want uninitialized values, zeros, random values, or random integers.


In [7]:
t1 = torch.empty(2, 3)
t2 = torch.zeros(2, 3, dtype=torch.int)
t3 = torch.randint(0, 10, [2, 3])

print(t1.shape)
print(t2.dtype)
print(t3)


torch.Size([2, 3])
torch.int32
tensor([[4, 5, 9],
        [2, 3, 1]])


## Task 2: Shapes and dimensions

Use `.size()` and `.dim()` to understand the structure of a tensor before applying any operation.

For a tensor `x = torch.rand(5, 4, 3)`, write the outputs of:

- `x.size()` -> torch.size([5,4,3])
- `x.dim()` -> 3

Also answer: Why is checking the shape one of the first things you should do when debugging tensor code?


## Task 3: NumPy to PyTorch and back

PyTorch and NumPy can share data easily. This is useful when your data starts in NumPy and you want to move it into PyTorch for training.


In [8]:
arr = np.ones([2, 3])
t = torch.from_numpy(arr)
back = t.numpy()

print(t)
print(back)


tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
[[1. 1. 1.]
 [1. 1. 1.]]


## Task 4: In-place operators

An in-place operator changes the tensor itself instead of creating a new one. These are common in PyTorch, but they should be used carefully.


In [9]:
t7 = torch.ones(2, 3, dtype=int)
t8 = torch.ones(2, 3, dtype=int)
t9 = torch.add(t8, t7)
t9.add_(t8)

print(t9)


tensor([[3, 3, 3],
        [3, 3, 3]])


## Task 5: Reshaping

Reshaping changes the view of a tensor without changing the number of elements. This is often needed before sending data into a fully connected layer.


In [10]:
t9 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t10 = t9.reshape(3, 2)

print(t10)
print(t10.shape)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


## Task 6: Pixels as numbers

Every image is really a grid of numbers called pixels. Computer vision models learn from these numbers instead of from the raw picture itself.

A grayscale MNIST image is 28 x 28.

1. How many pixel values does it contain? --> 784
2. Why is it useful to represent an image as a tensor instead of as a picture file?
--> because tensors allow operations and are useful inputs when it comes to neural networks 


## Task 7: Grayscale vs RGB images

Grayscale images use one channel. RGB images use three channels: red, green, and blue.

Write the usual tensor shape for:

- a grayscale image [1,H,W]
- an RGB image[3,H,W]

Also explain what each channel stores.
Each channel stores the intensity of the colour or grayscale 
1- grayscale
R- red
G- green
B -blue


## Task 8: Image tensor shape in PyTorch

PyTorch usually stores images in channels-first format.

What is the standard PyTorch image layout? [C, H, W]

Explain the difference between `[C, H, W]` and `[H, W, C]`.


## Task 9: Channels

Each color channel is a 2-D grid of numbers. Stacking the channels gives the full image.

Describe what the red, green, and blue channels represent in an RGB image. Why do three channels help a model understand color? 
they represent the intensity of the colours. all these channels help the model to differentiate one colour from another


## Task 10: Filters and kernels

A filter or kernel is a small grid of weights that looks for a pattern such as an edge or blur.


In [11]:
vertical_edge_kernel = torch.tensor([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
], dtype=torch.float32)

print(vertical_edge_kernel)


tensor([[-1.,  0.,  1.],
        [-2.,  0.,  2.],
        [-1.,  0.,  1.]])


## Task 11: Sliding window convolution

Convolution works by sliding a filter over the image, multiplying overlapping values, and summing them.

What is the role of stride in convolution? 
stride is the no. of pixels moved in each step so if the stride is large the output obtained is small



What do we get after applying the filter across the full image? 
we get a feature mao wherein it shows where the pattern was detected 


## Task 12: Feature maps

A feature map shows where a filter fired strongly in the input image.

If we apply several different filters to the same image, what do the outputs represent? the output gives us wherever the is a specific pattern the image and this is shown as the feature map 




Why are feature maps useful? it helps the model get data about where in the image there is an edge or other details regarding the visual part of the image 


## Task 13: Flattening images

A fully connected layer expects a 1-D vector, so the image must be flattened first.


In [12]:
x = torch.rand(64, 1, 28, 28)
x = x.view(-1, 784)

print(x.shape)


torch.Size([64, 784])


## Task 14: Simple fully connected classifier

The simplest classifier for MNIST often uses flattening, one hidden layer, ReLU, and a final output layer.


In [13]:
class FCClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 10),
        )

    def forward(self, x):
        return self.net(x)


## Task 15: Loss function and optimizer

Classification models usually use cross-entropy loss and an optimizer such as Adam.


In [14]:
model = FCClassifier()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


## Task 16: Loading MNIST with torchvision

The torchvision dataset utilities can download MNIST and apply a transform automatically.


In [15]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_dataset = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=transform,
)

print(len(train_dataset))


100.0%
100.0%
100.0%
100.0%


60000


In [18]:


train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True
)

## Task 17: DataLoader batch shapes

A DataLoader groups samples into batches and can shuffle them each epoch.

If `batch_size=64` and `images, labels = next(iter(train_loader))`, what are the shapes of `images` and `labels` for MNIST? Why does `images` have 4 dimensions?
images - torch.Size([64,1,28,28])
labels - torch.Size([64])
images has four dimensions because batch size, channel , height and breadth 

## Task 18: Transforms and augmentation

Transforms prepare data for the model, and augmentation makes the model see varied versions of the training images.


In [16]:
aug = transforms.Compose([
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])


## Task 19: Why augment only the training set?

Augmentation should help the model generalize without changing the test data distribution.

Why do we usually apply augmentation only to training images and not to test images? we do not apply it to test images as that data is for evaluating the performance of the model in the real world if that is also fed into the model then it would result in overfitting 


## Task 20: Training and evaluation workflow

Training updates the weights, while evaluation measures performance without tracking gradients.


In [19]:
for epoch in range(5):
    for images, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

model.eval()
with torch.no_grad():
    outputs = model(images)
    _, predicted = torch.max(outputs, 1)
